---
# Execution
# cp -v $KUBECONFIG .
# /Users/rbohne/.kube/.switch_tmp/config.2962012707.tmp -> ./config.2962012707.tmp
# export K8S_AUTH_KUBECONFIG=$(basename $KUBECONFIG)
# ansible-navigator run playbook-vm.yaml

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    namespace: rbohne-kubevirt-ansible
  tasks:

    - name: Deploy VM
      kubevirt.core.kubevirt_vm:
        state: present
        run_strategy: Always # default
        wait: true
        name: rhel9
        namespace: "{{ namespace }}"

        data_volume_templates:
          - metadata:
              name: rhel9-root
            spec:
              storage:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 30Gi
              sourceRef:
                kind: DataSource
                name: rhel9
                namespace: openshift-virtualization-os-images
        spec:
          volumes:
            - name: root
              dataVolume:
                name: rhel9-root
          networks:
            - name: coe
              multus:
                networkName: coe-bridge
          domain:
            cpu:
              cores: 2
            memory:
              guest: 4Gi
            resources:
              requests:
                memory: 4Gi
            devices:
              disks:
                - name: root
                  bootOrder: 1
                  disk:
                    bus: virtio
              interfaces:
                - bridge: {}
                  model: virtio
                  name: coe
